# Generated by Django 5.1.4 on 2025-02-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
